# Generated by Django 2.2 on 2021-01-03 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('splitting_category', models.CharField(choices=[('equally', 'Equally'), ('by_percentage', 'By Percentage'), ('by_amount', 'By Amount')], max_length=16)),
                ('notes', models.TextField(default=None, null=True)),
                ('comments', models.TextField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expense', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='accounts.Group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_for_expense', to=settings.AUTH_USER_MODEL)),
                ('shared_with_users', models.ManyToManyField(related_name='part_of_expense', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'db_table': 'api_expense',
            },
        ),
        migrations.CreateModel(
            name='LedgerTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('expense', 'Shared an Expense'), ('settlement', 'Did a Settlement')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_lt', to=settings.AUTH_USER_MODEL)),
                ('credit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_to_lt', to=settings.AUTH_USER_MODEL)),
                ('debit_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_from_lt', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_lt', to='expense.Expense')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_lt', to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Ledger Timeline',
                'db_table': 'api_ledger_timeline',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_to_ld', to=settings.AUTH_USER_MODEL)),
                ('debit_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_from_ld', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_ld', to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Ledger',
                'db_table': 'api_ledger',
            },
        ),
    ]
