# Generated by Django 2.2 on 2021-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
