# Generated by Django 2.2 on 2021-01-02 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('expense', 'Shared an Expense'), ('settlement', 'Did a Settlement')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_lt', to=settings.AUTH_USER_MODEL)),
                ('credit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_to_lt', to=settings.AUTH_USER_MODEL)),
                ('debit_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_from_lt', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_lt', to='expense.Expense')),
            ],
        ),
    ]
